"""create one-time planning records

Revision ID: 2921b44cad5b
Revises: 0006_remove_account_updated_at
Create Date: 2026-10-01 15:00:17.372066
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2921b44cad5b"
down_revision: str | None = "0006_remove_account_updated_at"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planned_commitments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ARS",
                "USD",
                name="planned_commitments_currency",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=7), nullable=False),
        sa.Column("recurrence", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recurrence = 'ONE_TIME'", name="ck_planned_commitments_recurrence"
        ),
        sa.CheckConstraint("status = 'PLANNED'", name="ck_planned_commitments_status"),
        sa.CheckConstraint("amount > 0", name="ck_planned_commitments_positive_amount"),
        sa.CheckConstraint(
            "length(trim(description)) > 0", name="ck_planned_commitments_description"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_planned_commitments_user_date_id",
        "planned_commitments",
        ["user_id", "due_date", "id"],
        unique=False,
    )
    op.create_table(
        "planned_income",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "ARS",
                "USD",
                name="planned_income_currency",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expected_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=7), nullable=False),
        sa.Column("recurrence", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recurrence = 'ONE_TIME'", name="ck_planned_income_recurrence"
        ),
        sa.CheckConstraint("status = 'PLANNED'", name="ck_planned_income_status"),
        sa.CheckConstraint("amount > 0", name="ck_planned_income_positive_amount"),
        sa.CheckConstraint(
            "length(trim(description)) > 0", name="ck_planned_income_description"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_planned_income_user_date_id",
        "planned_income",
        ["user_id", "expected_date", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_planned_income_user_date_id", table_name="planned_income")
    op.drop_table("planned_income")
    op.drop_index(
        "ix_planned_commitments_user_date_id", table_name="planned_commitments"
    )
    op.drop_table("planned_commitments")
    # ### end Alembic commands ###
